#!/bin/bash

if [ "$#" -ne 1 ]; then #if there are more than 1 arguments
    echo "Usage: $0 <4-digit-integer>"
    exit 1
fi

if ! [[ "$1" =~ ^[0-9]{4}$ ]]; then #if input is not a 4 digit int
    echo "Error: Please provide a valid 4-digit integer."
    exit 1
fi

#input: 4-digit integer
input_integer=$1

#hash the int with SHA-256 algorithm
hashed_value=$(echo -n "$input_integer" | sha256sum | awk '{print $1}') #print result

echo "Input: $input_integer"
echo "Hash: $hashed_value"
